### ISSUE TITLE
Characters break when selecting a position [BUG]

### ISSUE THREAD

**Issue by KyRLykaios** [ErinaSugino/Starbound-SBR-Mod#106]
## Describe the bug
> A clear and concise description of what the bug is. What is happening, under what circumstances is it happening, what are you expecting to happen, how can one reproduce this issue? No detail is too small.

Actor2 disappears while my character stays present when selecting any position besides Doggystyle OR standing position
This was tested with a Mechineki + Human,  then again with a Kitsune + Canera   (Same issue listed above happened with the Kitsune and Canera, although I noticed a  Kitsune and Mechineki couldn't initate sex between eachother if thats some sort of compat issue)
Mods Folder -  
![image](https://github.com/ErinaSugino/Starbound-SBR-Mod/assets/76587220/07f89521-19c6-49d5-b915-dd2255a6e385)

<br>

## Log File
> Attach your starbound.log file for the game session in which the error occured.
> The logfile is found in `<Starbound install folder>/storage/starbound.log`
> When file extensions are disabled, it's a **text file** simply called "starbound".

> *Make sure **info** and **debug** level logging is enabled in your main sexbound config.*
> *When playing on a server, the server log will be needed.*
> *In order to make tracing potential errors easier, use log files where you did as little as possible other than triggering the error.*

[starbound.log](https://github.com/ErinaSugino/Starbound-SBR-Mod/files/15428798/starbound.log)

**Comment by KyRLykaios** [comment]
That log didn't actually seem to have anything substantial.. so heres one I grabbed from D:\SteamLibrary\steamapps\common\Starbound\logs
[starbound.log](https://github.com/ErinaSugino/Starbound-SBR-Mod/files/15429031/starbound.log)

**Comment by ErinaSugino** [comment]
Error log says your animation file is missing the transformationGroup "actor2Ears" - which I can confirm is present, as intended, in both animation files of SBR.

So either there is some sneaky stuff that I missed, or another mod is messing with things.

So, as further troubleshooting - which object were you attempting to do it on?

**Comment by KyRLykaios** [comment]
A vanilla wooden bed item with a T1 SxB addon

**Comment by ErinaSugino** [comment]
I don't see anything wrong with it, uses the normal twoactors-centered animation file.
Does it work on a clean install of just SBR?

**Comment by KyRLykaios** [comment]
Tried a fresh install with just the Human, Neki and Kitsune race installed (and the  race menu extender as to not break the game,)

and still this in the log [12:22:09.172] [Error] [string "/scripts/sexbound/lib/sexbound/actor.lua"]:469: (MapException) Key 'actor2Ears' not found in OrderedMap::get()

Used aphrodites bow this time

**Comment by ErinaSugino** [comment]
Cross-checking your log with another report I got earlier, these are the non-Steam mods that overlap between the two of you:
sexbound_kitsunerace
sxbmechit
Aphrodite's Bow + patch
SexboundAPI_GiCcute
SxB_Canera
pov_redux
NekiSxB
LewdFluidDesc

**Comment by KyRLykaios** [comment]
Seems to not happen anymore after removing POV addons

**Comment by ErinaSugino** [comment]
You mean addon as in "SxB - HYLOTL POV", or as in POV Redux itself?

**Comment by ErinaSugino** [comment]
So, the GIC Sexbound support is causing this issue.
It currently contains old animation files for no reason, overwriting the new SBR 1.2 ones.
The reason it primarily happens with the Neki is because they are the only species who might currently utilize the ears layer.
