### ISSUE TITLE
[BUG] Sexui doesn't work

### ISSUE THREAD

**Issue by BlackusPL** [ErinaSugino/Starbound-SBR-Mod#132]
## Describe the bug
When you try prefer any activity that activate sexui, sexui shows in half transparent and no options is available.

<br>

## Log File
[starbound.log](https://github.com/user-attachments/files/17176614/starbound.log)

<br>

## Additional context

This happening in 1.2_r1. In 1.2_h1 doesn't happend and works fine.

<br>

**Comment by ErinaSugino** [comment]
[a1aed8e](https://github.com/ErinaSugino/Starbound-SBR-Mod/commit/a1aed8e7196228f57d790a00c2aac1a2340f5ab7)

**Comment by BlackusPL** [comment]
Still doesn't work

[starbound.log](https://github.com/user-attachments/files/17179169/starbound.log)
