### ISSUE TITLE
[REQUEST] Protogen Compatibility

### ISSUE THREAD

**Issue by Isekaid** [ErinaSugino/Starbound-SBR-Mod#140]
## Description
I would like to request if you can  add compatibility for the protogen mod made by Bun on the steam workshop. im not sure how it works behind the scenes but if you cant its ok
<br>

## Reason
Horny toasters - Jokes aside, i just think that it would be really cool to have such a thing as me and a friend are planning to make a colony in a space station with all the races, protogens being one of them and having kids of all sort wondering around would really add character to such a thing.
<br>

## Have you checked existing requests?
i am aware that dupes will be ignored, and yes i have checked to see if there is any.
<br>

## Additional context
as you previously read i am planning to make a colony with my friend, so i guess in a way this is more of a selfish thing, but other people may have the same or plans for late game.

As for concept images, i cant draw so i cant show anything of that sorts but here is what the actual protogens from the mod look like >

![image](https://github.com/user-attachments/assets/a8467b3b-2760-40b0-b21e-be2fa6f6bd32)

Also to be more speciffic this is the exact mod im on about > 
![image](https://github.com/user-attachments/assets/029c69a5-d83a-4907-8d7f-9c276aa12c51)

<br>

**Comment by ErinaSugino** [comment]
I understand your interest in supporting a specific race you play with, however there are two problems with your request.

First, this is not Sexbound's job. Sexbound itself will always only support the vanilla species, as to not bloat the filesize with potential compatibility with a race a player may or may not have installed. So your question is better asked elsewhere, like the Discord or the LL thread specifically for race compatibilities.

Second, in order for a race compatibility patch to be created, active consent to do so must be given by the race mod's author. I have no current information on such permission being asked for, let alone granted, for the Protogen race.
