### ISSUE TITLE
[REQUEST] Drawables Functionality

### ISSUE THREAD

**Issue by DrArtus** [ErinaSugino/Starbound-SBR-Mod#16]
Seeing that if a player has custom emoteDirectives or hairDirectives, SxB nodes still lag (though, not as long as old SxB would), and render the player invisible. I believe it would add a whole new level of fun immersion of custom assets such as player drawables were supported.

**Comment by ErinaSugino** [comment]
That loading sexnodes can take a moment and as such "lag" the game is normal, it's Starbound and noone can change anything about its shitty, single-threaded performance.

As for directives, nothing has been changed in comparison to old SxB in the way the loading of assets and rendering works - it still uses the exact same things the actual in-world entity uses; If and if so why there should be any loading time differences I don't know.

If the actor turns invisible at any point that is a bug, most likely related to a script crash inside the sexnode logic - but without you following standard bug reporting procedures and providing *a log* I cannot help you there.


As for the final part - "player drawables" - I have absolutely no idea what you are talking about.
