### ISSUE TITLE
[BUG] Nodes don't work

### ISSUE THREAD

**Issue by Necratine** [ErinaSugino/Starbound-SBR-Mod#19]
**Describe the bug**
I have installed the following mods:
-Sexbound Reborn 1.0_r1h1
- Aphrodite's Bow (WITH PATCH)
- Lustbound
- Sexbound-Globaura-2.1
- Fuchsia the Floran Slut 0.3.2 for v3
- sexbound-EBs Lovely Whips1.0.5

Simply the nodes don't works, when i used the node and quit up, i can't use the same node again, i've installed the SBR at detail but, don't works, i tried to check if workshop mods are provoking an error, my workshop mods are the following: (attached images) 

Also i will share videos to better explain the bug
thanks and sorry for the problems

**Log File**
[starbound.log](https://github.com/ErinaSugino/Starbound-SBR-Mod/files/11361521/starbound.log)

**Additional context**
https://drive.google.com/file/d/1GywyI1DRx7rTndvJc_7U56eUey1kv2u6/view?usp=share_link
https://drive.google.com/file/d/1FlfKZu01LGnmZt7RyOLaXfVCCKYzkglz/view?usp=share_link

![imagen_2023-04-29_221243044](https://user-images.githubusercontent.com/132182028/235335163-6b554f8b-dbb9-49b8-bdc7-0ce49deebec8.png)
![imagen_2023-04-29_221257904](https://user-images.githubusercontent.com/132182028/235335170-f6d0655a-ee99-43a5-9fc7-d7ef0a35902e.png)
![imagen_2023-04-29_221311584](https://user-images.githubusercontent.com/132182028/235335177-491d0001-5e3a-4df7-b2e8-67ca29fc202a.png)
![imagen_2023-04-29_221322926](https://user-images.githubusercontent.com/132182028/235335183-7f198720-ad8f-4f5e-b1e7-ad25818e776b.png)

![imagen_2023-04-29_221147924](https://user-images.githubusercontent.com/132182028/235335138-8cd346eb-1ce2-41ae-8339-ae03fae1831b.png)

**Comment by ErinaSugino** [comment]
You have the Lustbound patch installed wrongly - you spilled all the contents over the mods folder, which is why it isn't working.

**Comment by Necratine** [comment]
> You have the Lustbound patch installed wrongly - you spilled all the contents over the mods folder, which is why it isn't working.

Oh my bad, thanks and sorry for the inconveniences.
