### ISSUE TITLE
How to add a new language to SBR?

### ISSUE THREAD

**Issue by abcdefg233** [ErinaSugino/Starbound-SBR-Mod#21]
![image](https://github.com/ErinaSugino/Starbound-SBR-Mod/assets/32760059/57f2178a-b534-44af-80d2-8f69349b2bda)
I noticed that the "starbound.config" file has a "supportedLanguages" section that currently includes English and Russian languages.
I would like to add a new language to SBR. But I'm not sure how is "supportedLanguages" work.

**Comment by ErinaSugino** [comment]
Here is a detailed guide on how to create a translation mod:
https://github.com/ErinaSugino/Starbound-SBR-Mod/wiki/Modding:-Translations

**Comment by abcdefg233** [comment]
Well, that helps
