### ISSUE TITLE
[BUG] Player Pregnancy Issues

### ISSUE THREAD

**Issue by Mikorsa** [ErinaSugino/Starbound-SBR-Mod#48]
**Describe the bug**
Pregnancy only happens with NPCxNPC not PlayerxNPC.

**Log File**
[starbound (3).log](https://github.com/ErinaSugino/Starbound-SBR-Mod/files/12542051/starbound.3.log)

**Additional context**
The thing seems to be working with NPCxNPC and creates the baby sucsefully, not NPCxPlayer however, doesn't matter if the player is imprеgnating or getting imprеgnаted.

**Comment by 777joshua7771** [comment]
I seem to run into a same sorta problem Mikorsa is having, and would like to help out narrowing down the error if it hasn't been identified.

From what i've changed from the sexbound.config file to enable more log options and on a fresh install, This seem to caught my eyes whenever a "Successful" impregnation is occurred, even if it being a NPCxNPC or NPCxPlayer for my experience.
![notepad++_yz63hZSbws](https://github.com/ErinaSugino/Starbound-SBR-Mod/assets/93668917/6d1be95c-0d68-41f5-b632-b5faab9203cb)

**Comment by ErinaSugino** [comment]
Oh boi, that screams like trouble

**Comment by 777joshua7771** [comment]
It's definitely is screaming out trouble from the look of it, and i would be glad to help further with the pregnancy issue.

**Comment by ErinaSugino** [comment]
The current issue has already been fully identified - _Starbound does not give us access to the Global Context Variable_.
Best case scenario: I just have to read deeper into the topic of environment variables to find the right (and accessible) one.
Worst case scenario: I have to rework or even scrap the entire modularization of pregnancy types.

**Comment by 777joshua7771** [comment]
Ahh, then I will like to wish you and other contributors well, hoping of the best case scenario result, the idea of it alongside the reworked pregnancy system sparked my interest with the SBR mod overall. ^^

**Comment by ErinaSugino** [comment]
Uploaded new zip for Build 1 including the aforementioned changes. The mechanic can now be properly tested. If no other issues arise the issue is solved.

**Comment by 777joshua7771** [comment]
Hey, back again to test it out after a fresh install of the changed build in hope of it having no issue. However, it's seem to went in a same sorta dead end with the nil value being different than the previous.
![notepad++_dgHJi9sqky](https://github.com/ErinaSugino/Starbound-SBR-Mod/assets/93668917/dc075932-5dee-4294-bb15-3b4a3c987a89)

**Comment by 777joshua7771** [comment]
Not really sure on what Field it seem to finding nil when I was looking into my logs, but maybe one of the field might be incorrect?

**Comment by ErinaSugino** [comment]
\*sigh\*
Ok, here is another try. Tested it myself until I got a successful pregnancy.

**Comment by 777joshua7771** [comment]
Getting pregnant is working for me on another install of the fresh build, which worked well enough. Though another issue and two error logs seem to occur now during the pregnancy and finally the birthing part. Not really sure if there any work in progress stuff is needed for it, but seems important enough for me to point it out.

![image_2023-09-25_204005838](https://github.com/ErinaSugino/Starbound-SBR-Mod/assets/93668917/87c0600f-b855-4acc-a4c7-539c383bbffa)

**Comment by ErinaSugino** [comment]
The errors of these two specific lines have been fixed.

**Comment by 777joshua7771** [comment]
Hell, fixes after fixes it seem to get quite worse with a few outdated coding i assume? With that latest one seem to start causing NPCS to despawn and drop their loots, even when freshly spawned ones.
Plus, the error line seem to be too long for me to post a screenshot, and the most recent spawn i had done is the latest.

[starbound.log](https://github.com/ErinaSugino/Starbound-SBR-Mod/files/12716674/starbound.log)

And with these constant errors after fixes, i don't know how much more error after this one get fixed .3.

**Comment by ErinaSugino** [comment]
That one has actually nothing to do with pregnancies and is from the new features of Build 2.
Fixed the syntax error.

I can also exactly explain to you what's going on: At some point I moved code from one place to another. Which means variable references change. But since Lua is crap and I only work with Notepad++, I don't have refactoring mechanism available, and so it's quiet easy to miss a single reference somewhere that still points to the old structure. I also usually do only theory-coding - write the code as it should "theoretically work", then upload it for other's to find out if it actually does. That's why there may be a million lines that need fixing, and you can only find them one by one.

If theres more clean syntax errors in Build 2 though, I'll take a look over it myself until the game at least boots stably again.

**Comment by 777joshua7771** [comment]
Gotcha, so would i start up a new issue of the later errors and bugs regarding of the NPC and new features?

**Comment by ErinaSugino** [comment]
You can slap all the generic Syntax errors and stuff that obviously only broke now into the [Discussions Thread](https://github.com/ErinaSugino/Starbound-SBR-Mod/discussions/51)

**Comment by ErinaSugino** [comment]
Edit, colors might be fixed.

**Comment by ErinaSugino** [comment]
New Upload

**Comment by ErinaSugino** [comment]
Did using the birthing pill in this instance actually spawn the NPC? Full log?

Also, do you mean the pregnancy test itself outputs 7000 days as radio message, or that the log says "birthWorldTime" = 7000+? The latter would be normal for player pregnancies, as that's seconds.

**Comment by ErinaSugino** [comment]
Again, I need the log.
