### ISSUE TITLE
[REQUEST] Compatibility with "Frackin' Universe"

### ISSUE THREAD

**Issue by Golyath160** [ErinaSugino/Starbound-SBR-Mod#53]
Hello, is it possible to make "Sexbound Reborn" compatible with the "Frackin' Universe" mods? 

I tried to add SBR to my party but I came across a problem: when I go to a bed to unleashed a sex scene the menu doesn't appear; but everything works on a party that has only SBR. 

Thank you in advance.

**Comment by ErinaSugino** [comment]
Two parts.

Part 1: Compatibility with Frackin Universe is already given to the highest extend possible - that is, both Sexbound and FU can coexist installed at the same time. The owner of FU hates the adult modding community to the core (even more so than any other human being in the world), and has in the past already made modifications to FU specifically to break Sexbound just to prevent people from ever using it. We will not ever try to work with that mod again - if something isn't broken, don't fix it.

Part 2: With that said, both mods in their current state should work. As such, the error that "the menu doesn't appear" shouldn't happen - at worst all of FU's new NPCs are not fuckable. For everything else it still works.
So there might be something else going on - if you want to look into it, go to the [Trouble Shooting](../discussions/categories/trouble-shooting) forum and open a thread, the we'll see what we can do.
