### ISSUE TITLE
[REQUEST] "Pseudo-Hardcore" tweak that makes it so if your character dies in hardcore, you switch control to a child you are the parent of

### ISSUE THREAD

**Issue by CorvusButWeird** [ErinaSugino/Starbound-SBR-Mod#81]
## Description
> Making it so if you have kids in this mod, you will take control of them rather than having the game end when you die in hardcore mode.

<br>

## Reason
> I think that this would not only add an interesting spin on existing difficulty options, but it would tie the mod into the gameplay loop.

<br>

## Have you checked existing requests?
> I have checked and I haven't seen anything.

<br>

## Additional context
> No further comment.

<br>

**Comment by ErinaSugino** [comment]
That idea is a lovely one. Sadly, there is one slight problem with it:
It is utterly impossible. By any normal means, at least.
The player is 100% uneditable after creation. So is the hardcoded logic of the gamemodes, including how "permadeath" handles, well, death. I can think of potential hacks to attempt to work around that, but that doesn't solve the main issue. NPCs only exist in any meaningful form when they are loaded in. So unless you keep the entire data of every child you produce, fetching their existence to "take them over" would only work if you'd die directly next to them.

All of these problems _could_ be negated by using more intrusive means, like rewriting the game itself as projects such as StarExtensions and OpenStarbound are doing - however, the former has too much dead weight forcibly included to be a reasonble hard dependency and OpenStarbound is in too much of a fragile state right now for me to consider relying on it.
Me and come collaborators are trying our hands at our own spin on the "rework Starbound" mod, however we have yet to reach any state of usability.

So for now, this idea is sadly fully impossible.

**Comment by CorvusButWeird** [comment]
Understood. I figured it was worth a shot lmfao.
