### ISSUE TITLE
[BUG] Incompatibility with "Anom's Outpost Overhaul"

### ISSUE THREAD

**Issue by CorvusButWeird** [ErinaSugino/Starbound-SBR-Mod#82]
## Describe the bug
> The condom dispenser that is usually in the bathroom of the vanilla outpost is now on the ceiling of a random room in the overhauled outpost
![image](https://github.com/ErinaSugino/Starbound-SBR-Mod/assets/156613571/88430d3b-d7f8-4255-945b-818c4608ebc2)

<br>

## Log File
> Not applicable, considering this is just a placement issue.

<br>

## Additional context
> With how popular Anom's Outpost Overhaul is, and the number of compatibility patches already out there, perhaps a patch or inbuilt compatibility to ensure that the condom dispenser actually in the bathroom of the new outpost layout would be a worthwhile addition.

<br>

**Comment by ErinaSugino** [comment]
Having the coordinates of the bathroom - if any exists in that outpost version - would be handy.

**Comment by CorvusButWeird** [comment]
> Having the coordinates of the bathroom - if any exists in that outpost version - would be handy.

Oh shit only saw this now, sorry. one moment.

**Comment by CorvusButWeird** [comment]
There is probably a better and more certain way to do this, but standing at the entrance of the left bathroom gives me the coords 399, 582, and the coords 449, 582 in the entrance of the right bathroom, when I run the position command using StarExtensions and the [SE] Quick Commands! mods. I hope this at least helps a little. If there's a better way to do this please let me know, I'm still new to the technical side of Starbound and I'd love to learn how to do this stuff.
![image](https://github.com/ErinaSugino/Starbound-SBR-Mod/assets/156613571/bd4ca2e2-e6ed-4294-862e-107c32761fcb)

**Comment by ErinaSugino** [comment]
By using `/admin` and `/debug` you get the debug overlay, which contains the property "player_aim". That's the exact location of your cursor. By doing that, I need the top left corner of a free 2x2 space in the men's bathroom, to insert the condom dispenser there.

**Comment by CorvusButWeird** [comment]
oooh alright, thanks for explaining. 443, 584 for the top left portion of the square in this position. Figured this spot would make the most sense.
![image](https://github.com/ErinaSugino/Starbound-SBR-Mod/assets/156613571/61a16b8a-e49f-497b-a8bd-951512258a49)

**Comment by ErinaSugino** [comment]
Try this and tell me if it is correct.

**Comment by CorvusButWeird** [comment]
I assume I just download this patch and replace the file with the same name in the sexbound folder with, correct? If so, it still isn't showing up.

Maybe this will help, unless you've already looked at it? https://steamcommunity.com/workshop/filedetails/discussion/2468903056/3124911622561438399/

**Comment by ErinaSugino** [comment]
You apply the changes from the commit to the affected file manually. If it doesn't work there should be something in the log telling the patch isn't applied because of a parsing error.

Also, I know the thread you linked. The guy asking for if there is a parameter to test for in that file? Literally me.

**Comment by CorvusButWeird** [comment]
Ohhh I see. Sorry, still kinda new at this. I pasted it in like this, is this right? Either way it had no effect regardless, it still ain't there.
![image](https://github.com/ErinaSugino/Starbound-SBR-Mod/assets/156613571/73a31fb6-d818-4f63-8f99-da5ebf06a2f2)

**Comment by ErinaSugino** [comment]
Don't know why your "op": "add" is highlighted green, but looks right.

Depends on what "isn't there" means now.
If nothing is there, I need the log file.
If the dispenser is still at the previous location, I'll need to use a different approach.

**Comment by CorvusButWeird** [comment]
Well it's no longer at the previous location
![image](https://github.com/ErinaSugino/Starbound-SBR-Mod/assets/156613571/4548b6e7-1817-4217-80df-9d6d723fe018)

But its not at the desired one either.

I did a quick skim through the log, the error I think we are looking for is at [22:01:21.715], but the error itself is all greek to me.
[starbound.log](https://github.com/ErinaSugino/Starbound-SBR-Mod/files/14274832/starbound.log)

I *am* running an instance with a large number of mods, but with the only other outpost mods I have installed being other patches for Anom's Outpost Overhaul for other mods, none of which touch its bathrooms, I don't think this should be the problem.

**Comment by CorvusButWeird** [comment]
Should I get a fresh version of the file to apply these changes to, or just do these on top of the one I already have? Just want to verify.

**Comment by ErinaSugino** [comment]
You can follow the incremental steps of the commit, do it on a fresh file or just copy the entire file into an empty one. Your choice. At the end the contents just have to be exactly as on GitHub.

**Comment by CorvusButWeird** [comment]
copied the entire file, and it still isn't working. Its currently in the previous position, but still not in the bathroom.

**Comment by ErinaSugino** [comment]
This should then certainly work now (unless I made a syntax error)

**Comment by CorvusButWeird** [comment]
I would assume that there is indeed a syntax error
![image](https://github.com/ErinaSugino/Starbound-SBR-Mod/assets/156613571/72ea375a-74ec-4027-9da7-bc3928f2e940)

**Comment by ErinaSugino** [comment]
*sigh*
Try again now.

**Comment by CorvusButWeird** [comment]
This *is* correct, right? Idk if you changed the last commit or did something else.
![image](https://github.com/ErinaSugino/Starbound-SBR-Mod/assets/156613571/e1b31885-ba7e-4478-a85f-6657d4187933)

**Comment by ErinaSugino** [comment]
Yes, I made a new commit.
No, that's not right. That's the version with the missing `,` causing the syntax error crash.

**Comment by CorvusButWeird** [comment]
Ok so where do I find the new commit? All I can see is the ones you previously posted, am I just missing how github works?

**Comment by ErinaSugino** [comment]
You go to the `Code` tab, switch to the `V1.2` development branch, then click on the commit history. There you'll find this last commit I did on it 5758ae3

**Comment by CorvusButWeird** [comment]
I still cant get it to work, even with the bare essentials to actually make testing not a hassle. These are the ONLY mods I am testing with right now. At this point I am honestly at a loss.
![image](https://github.com/ErinaSugino/Starbound-SBR-Mod/assets/156613571/36dba032-e693-4cd0-b1d1-f82076bac64c)

**Comment by ErinaSugino** [comment]
I just realized something.
Mod loading priority.
I'll need to make this a seperate mod that loads after Anom's Outpost Overhaul.

**Comment by CorvusButWeird** [comment]
Applied those changes and tried running it. No change.

I must ask, is having both ""AnomsOutpostOverhual" and "AnomsOutpostOverhaul", and the former being "ua" instead of "au" intended? This isn't trying to sound snarky, Idk how modding works so I just wanna be sure there isn't some reason why that is there.

**Comment by ErinaSugino** [comment]
The typo is in the mod's id, atleast judging from your last log. I put the right version in case it has been or will be fixed in the future.
