### ISSUE TITLE
[REQUEST] Compatibility with "Elithian Races"

### ISSUE THREAD

**Issue by Shigess** [ErinaSugino/Starbound-SBR-Mod#85]
## Description
> Good morning or evening, I wanted to suggest or ask if it is possible to add a compatibility patch between "Sexbound Reborn" and "Elithian Races", specifically the race of that "Avikan" mod. (https://steamcommunity.com/workshop/filedetails/?id=850109963), (https://github.com/Aegonian/ElithianAllianceStarboundMod).

<br>

## Reason
> I know that the mod will not crash if both are used together, but my request is focused on correctly interacting the SxB mechanics with the race in question.

<br>

## Have you checked existing requests?
> Yes.

<br>

## Additional context
> Elithian Races has four complete races to date, Trinkets, Droden, Aegi and Avikan, the first two are droids, the third is a customized human without much difference but the last one is practically the most important and different, it would be great if it could work with SxB mechanics.
![imagen_2024-01-27_135303762](https://github.com/ErinaSugino/Starbound-SBR-Mod/assets/157892187/dbe0305f-2bf7-4008-9d87-fb36d2afefaf)

<br>

**Comment by ErinaSugino** [comment]
Thank you for the detailed request - however, I'm afraid you're asking the wrong person.

First off, Sexbound itself will only ever support the game's vanilla races. All the compatibility patches are made by other people. I'm also not an artist, so I couldn't create a proper race support patch even if I wanted to.

Secondly, race support patches require the author's permission to do so. I don't know how up-to-date this list is, but here you can see a big overview about races and their status. Elithian Races are marked as "nope".
[https://docs.google.com/spreadsheets/d/1kHYDblYaPt4Yp1fi_wcbxp7RVx4UBGXYyRNhqe5B2C8/view#gid=0](https://docs.google.com/spreadsheets/d/1kHYDblYaPt4Yp1fi_wcbxp7RVx4UBGXYyRNhqe5B2C8/view#gid=0)
Don't ask me why that is, I'm not informed in that regard, but if I had to take a wild guess it probably got something to do with their stand on Frackin' Universe.

So yeah, unless there is a bug with this race specifically - which should only matter if you already have a private use only, self-made compatibility patch yourself, there is nothing I can do.

**Comment by Shigess** [comment]
Thank you for your attention Erina, I had not taken into account the rest of the needs for a compatibility patch, in that case I hope that in the future the author or representatives give permission and that a kind soul wants to make the patch, thank you for your work with SxB
