### ISSUE TITLE
[REQUEST-QUESTION] Add configuration option to disable stats display

### ISSUE THREAD

**Issue by Shigess** [ErinaSugino/Starbound-SBR-Mod#86]
## Description
> It's a suggestion and a question:

> I want to suggest implementing an option to disable or hide the stats information, I understand why it is there, but I really don't like it, I would like to hide it.

> I want to ask, how can I hide/delete that information even if I have to touch a mod file?

<br>

## Reason
> Being a mod that seeks immersive-realism, that tab is unnecessary, I understand that some will like it, that is why I want to ask how I can disable it for myself and, in turn, suggest that a more practical option be implemented to remove or hide it.

<br>

## Have you checked existing requests?
> Yes.

<br>

## Additional context
> Nothing really, I want to keep my character's adventures a secret when I play with my people. Thank you for your time and attention, I really appreciate that you are paying attention to SxB, it is a great mod with a lot of effort and commitment behind it

<br>

**Comment by ErinaSugino** [comment]
If you want to simply remove the tab from the customizer UI where you can view your stats, that'd be as simple as removing the section from teh `customizer.config` in `/interface/sexbound/customizer/`.

If you want to fully remove statistical tracking for your entity, you need to edit `/scripts/sexbound/override/player.lua`, the `Sexbound.Player.new()` function and remove the line initing the statistics handler `self._statistics = Sexbound.Player.Statistics:new(self)` - as well as potentially other code references that expect that module to exist. While causing asset mismatching, this change only affects your local player entity and should even work on a server that has an unmodified copy.

However, albeit not my space to judge, I don't quiet understand what or why you are trying to achieve. You say you "want to keep your character's adventures a secret when playing with your people" - the statistics, by normal means, cannot be seen by another player.

**Comment by Shigess** [comment]
Thank you Erina, always so kind and diligent. Do you have a patreon or discord server?

**Comment by ErinaSugino** [comment]
Sexbound Reborn has it's own section on the general [Starbound Adult Modding Discord](https://discord.gg/AnZ7QA4BfR).
As for Patreon, I use KoFi - a link to which you can find on the GitHub "Sponsor" section right on the main page of the Repo.
