### ISSUE TITLE
[REQUEST] Arousal effect for PC

### ISSUE THREAD

**Issue by Antlion2** [ErinaSugino/Starbound-SBR-Mod#9]
As far as I am aware, arousal values for PC are tracked, but there's no way to see them. What I propose is to give the player a very minor "distracted" debuff with severity that would depend on a value (for example -5~15% movement speed penalty), which is then cleared after an act. For players that do not want this type of interaction, it then can be disabled it in config.
 In my opinion, such feature would add a much needed gameplay interaction since the current state is very sandboxy (outside of defeat mod).

**Comment by ErinaSugino** [comment]
I'll wait with this until the new positions are done, as to always have availability to get rid of the debuff without needing debug tools like Aphrodite's Bow to force NPCs. (e.g. Solo actor positions)

**Comment by ErinaSugino** [comment]
Forgot to ping. 9324311
