### ISSUE TITLE
[REQUEST] Could we get support for the github optimized version of starbound?

### ISSUE THREAD

**Issue by GeekyRaptor** [ErinaSugino/Starbound-SBR-Mod#91]
Could we get compatibility for the launcher introduced by this github repository: https://github.com/FezzedOne/xSB-2?tab=readme-ov-file

the launcher is known as xSB-2 and it is much more optimized than the vanilla launcher, however I noticed sexbound mods cause issues with this launcher. Some support would be greatly appreciated.

I think the optimized loading times and gameplay that is lag-less would make this a match made in heaven.

**Comment by ErinaSugino** [comment]
Any proper modified Starbound version should always have full compatibility with vanilla features. If it doesn't, supporting all possibly available custom Starbound version is just too much of a redundant task.

You can add more information on what exactly is not working and I can see if it's an easy fix, but I currently have no plans on maintining multiple Sexbound version for different "Starbounds".

**Comment by GeekyRaptor** [comment]
The game crashes before launch when I use the custom version of starbound
with the sex mods, I was hoping for a compatibility patch, tbh I am unsure
if I should ask them or you on this matter.

**Comment by ErinaSugino** [comment]
I'd need more precise information than that. A logfile and/or a screenshot of the crash message. Though in that case it is most likely a deeper problem.
